In [44]:
import pandas as pd

In [53]:
customers = pd.read_csv('../staging_1/customers/customers.csv')
len(customers)

1445

In [54]:
stores = pd.read_csv('../staging_1/stores/stores.csv')
stores.head()

,store_id,store_name,phone,email,street,city,state,zip_code,extraction_time,source_folder
0,1,Santa Cruz Bikes,(831) 476-4321,NaN,3700 Portola Drive,Santa Cruz,CA,NaN,2024-04-29 12:14:14.295277,datalake/bikestore_dim/stores
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432.0,2024-04-29 12:14:14.295277,datalake/bikestore_dim/stores
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088.0,2024-04-29 12:14:14.295277,datalake/bikestore_dim/stores

In [55]:
merged_df = pd.merge(customers, stores[['state', 'city','store_id']], on=['state', 'city'], how='left')
merged_df

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code,extraction_time,source_folder,store_id
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1440,1441,Jamaal,Morrison,NaN,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
1441,1442,Cassie,Cline,NaN,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
1442,1443,Lezlie,Lamb,NaN,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
1443,1444,Ivette,Estes,NaN,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN
1444,1445,Ester,Acevedo,NaN,ester.acevedo@gmail.com,671 Miles Court,San Lorenzo,CA,94580,2024-04-29 12:14:14.259868,datalake/bikestore_dim/customers,NaN

In [56]:
merged_df['local'] =~ merged_df['store_id'].isna()
merged_df['local'].value_counts()

False    1425
True       20
Name: local, dtype: int64

In [58]:
merged_df.to_csv('../staging_2/customers/customers.csv' , index= False)